
import { useLanguage } from "@/context/language-context";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Share2 } from "lucide-react";
import { MaterialQuantities } from "@/lib/calculations";

interface BillOfMaterialsProps {
    materials: MaterialQuantities;
    manualCeilingBoards: number | '';
    onCeilingBoardsChange: (value: number | '') => void;
    manualMainTees: number | '';
    onMainTeesChange: (value: number | '') => void;
    manualCrossTees: number | '';
    onCrossTeesChange: (value: number | '') => void;
    manualWallAngles: number | '';
    onWallAnglesChange: (value: number | '') => void;
    manualRivets: number | '';
    onRivetsChange: (value: number | '') => void;
    manualWire: number | '';
    onWireChange: (value: number | '') => void;
    manualNails: number | '';
    onNailsChange: (value: number | '') => void;
    ceilingBoardName: string;
}

const translations = {
  title: {
    si: 'අමුද්‍රව්‍ය ලැයිස්තුව',
    en: 'Bill of Materials',
    ta: 'பொருள் பட்டியல்',
  },
  description: {
    si: 'ඔබේ ව්‍යාපෘතිය සඳහා අවශ්‍ය වන ද්‍රව්‍ය.',
    en: 'Estimated materials required for your project.',
    ta: 'உங்கள் திட்டத்திற்கு தேவையான பொருட்கள்.',
  },
  item: {
    si: 'අයිතමය',
    en: 'Item',
    ta: 'பொருள்',
  },
  quantity: {
    si: 'ප්‍රමාණය',
    en: 'Quantity',
    ta: 'அளவு',
  },
  mainTee: {
    si: 'මේන් ටී 12\'',
    en: 'Main Tee 12\'',
    ta: 'மெயின் டீ 12\'',
  },
  crossTee: {
    si: 'ක්‍රොස් ටී 2\'',
    en: 'Cross Tee 2\'',
    ta: 'கிராஸ் டீ 2\'',
  },
  wallAngle: {
    si: 'වෝල් ඇන්ගල් 10\'',
    en: 'Wall Angle 10\'',
    ta: 'சுவர் கோணம் 10\'',
  },
  concreteNails: {
    si: 'කොන්ක්‍රීට් ඇණ 1.5"',
    en: 'Concrete Nails 1.5"',
    ta: 'கான்கிரீட் ஆணிகள் 1.5"',
  },
  wire: {
    si: 'කම්බි',
    en: 'Wire',
    ta: 'கம்பி',
  },
  rivets: {
    si: 'ඇලුමිනියම් රිවට්',
    en: 'Aluminum Rivets',
    ta: 'அலுமினிய ரிவெட்டுகள்',
  },
  boards: {
    si: 'බෝඩ්',
    en: 'Boards',
    ta: 'பலகைகள்',
  },
  pieces: {
    si: 'කෑලි',
    en: 'Pieces',
    ta: 'துண்டுகள்',
  },
  kg: {
    si: 'kg',
    en: 'kg',
    ta: 'கிலோ',
  },
  shareMessageTitle: {
    si: '*සිවිලිම් ව්‍යාපෘතිය - අමුද්‍රව්‍ය ලැයිස්තුව*',
    en: '*Ceiling Project - Bill of Materials*',
    ta: '*கூரை திட்டம் - பொருள் பட்டியல்*',
  },
  generatedBy: {
    si: '_Ceiling Ace මගින් ජනනය කරන ලදී_',
    en: '_Generated by Ceiling Ace_',
    ta: '_சீலிங் ஏஸ் மூலம் உருவாக்கப்பட்டது_',
  },
  downloadApp: {
      si: 'Ceiling Ace යෙදුම බාගන්න',
      en: 'Download Ceiling Ace App',
      ta: 'சீலிங் ஏஸ் செயலியைப் பதிவிறக்கவும்',
  }
};


const WhatsAppIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg
      role="img"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill="currentColor"
      {...props}
    >
      <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" />
    </svg>
);

export default function BillOfMaterials({ 
    materials, 
    manualCeilingBoards,
    onCeilingBoardsChange,
    manualMainTees,
    onMainTeesChange,
    manualCrossTees,
    onCrossTeesChange,
    manualWallAngles,
    onWallAnglesChange,
    manualRivets, 
    onRivetsChange,
    manualWire,
    onWireChange,
    manualNails,
    onNailsChange,
    ceilingBoardName
}: BillOfMaterialsProps) {
    
    const { language } = useLanguage();
    const displayedCeilingBoards = manualCeilingBoards !== '' ? manualCeilingBoards : materials.ceilingBoards;
    const displayedMainTees = manualMainTees !== '' ? manualMainTees : materials.mainTees;
    const displayedCrossTees = manualCrossTees !== '' ? manualCrossTees : materials.crossTees;
    const displayedWallAngles = manualWallAngles !== '' ? manualWallAngles : materials.wallAngles;
    const displayedRivets = manualRivets !== '' ? manualRivets : materials.rivets;
    const displayedWire = manualWire !== '' ? manualWire : materials.wireKilos;
    const displayedNails = manualNails !== '' ? manualNails : materials.concreteNails;

    const createChangeHandler = (setter: (value: number | '') => void) => {
        return (e: React.ChangeEvent<HTMLInputElement>) => {
            const value = e.target.value;
            setter(value === '' ? '' : parseInt(value, 10));
        };
    };

    const handleShare = () => {
        const items = [
            { name: ceilingBoardName, quantity: displayedCeilingBoards, unit: translations.boards[language] },
            { name: translations.mainTee[language], quantity: displayedMainTees, unit: translations.pieces[language] },
            { name: translations.crossTee[language], quantity: displayedCrossTees, unit: translations.pieces[language] },
            { name: translations.wallAngle[language], quantity: displayedWallAngles, unit: translations.pieces[language] },
            { name: translations.concreteNails[language], quantity: displayedNails, unit: translations.pieces[language] },
            { name: translations.wire[language], quantity: displayedWire, unit: translations.kg[language] },
            { name: translations.rivets[language], quantity: displayedRivets, unit: translations.pieces[language] },
        ];

        const messageBody = items
            .filter(item => item.quantity > 0)
            .map(item => `- ${item.name}\n\t${item.quantity} ${item.unit}`)
            .join('\n\n');
        
        const appUrl = window.location.origin;
        const downloadMessage = `${translations.downloadApp[language]}:\n${appUrl}`;

        const message = `${translations.shareMessageTitle[language]}\n\n${messageBody}\n\n${translations.generatedBy[language]}\n\n${downloadMessage}`;

        const encodedMessage = encodeURIComponent(message.trim());
        const whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
        window.open(whatsappUrl, '_blank');
    };

    return (
        <Card>
            <CardHeader className="flex flex-row items-center justify-between p-4">
                <div className="space-y-1">
                    <CardTitle className="text-xl">{translations.title[language]}</CardTitle>
                    <CardDescription className="text-sm">
                        {translations.description[language]}
                    </CardDescription>
                </div>
                <Button variant="outline" size="icon" onClick={handleShare}>
                    <WhatsAppIcon className="h-5 w-5" />
                    <span className="sr-only">Share to WhatsApp</span>
                </Button>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>{translations.item[language]}</TableHead>
                            <TableHead className="text-right">{translations.quantity[language]}</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        <TableRow>
                           <TableCell className="font-medium">{ceilingBoardName}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedCeilingBoards > 0 ? displayedCeilingBoards : ''}
                                        onChange={createChangeHandler(onCeilingBoardsChange)}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.quantity[language]}
                                     />
                                     <span>{translations.boards[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                         <TableRow>
                           <TableCell className="font-medium">{translations.mainTee[language]}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedMainTees > 0 ? displayedMainTees : ''}
                                        onChange={createChangeHandler(onMainTeesChange)}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.quantity[language]}
                                     />
                                     <span>{translations.pieces[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                        <TableRow>
                           <TableCell className="font-medium">{translations.crossTee[language]}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedCrossTees > 0 ? displayedCrossTees : ''}
                                        onChange={createChangeHandler(onCrossTeesChange)}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.quantity[language]}
                                     />
                                     <span>{translations.pieces[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                        <TableRow>
                           <TableCell className="font-medium">{translations.wallAngle[language]}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedWallAngles > 0 ? displayedWallAngles : ''}
                                        onChange={createChangeHandler(onWallAnglesChange)}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.quantity[language]}
                                     />
                                     <span>{translations.pieces[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                         <TableRow>
                           <TableCell className="font-medium">{translations.concreteNails[language]}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedNails > 0 ? displayedNails : ''}
                                        onChange={createChangeHandler(onNailsChange)}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.quantity[language]}
                                     />
                                     <span>{translations.pieces[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                        <TableRow>
                           <TableCell className="font-medium">{translations.wire[language]}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedWire > 0 ? displayedWire : ''}
                                        onChange={(e) => {
                                            const value = e.target.value;
                                            onWireChange(value === '' ? '' : parseFloat(value));
                                        }}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.kg[language]}
                                     />
                                     <span>{translations.kg[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                        <TableRow>
                           <TableCell className="font-medium">{translations.rivets[language]}</TableCell>
                           <TableCell className="text-right">
                                <div className="flex items-center justify-end gap-2">
                                     <Input 
                                        type="number"
                                        value={displayedRivets > 0 ? displayedRivets : ''}
                                        onChange={createChangeHandler(onRivetsChange)}
                                        className="w-24 h-8 text-right"
                                        placeholder={translations.quantity[language]}
                                     />
                                     <span>{translations.pieces[language]}</span>
                                </div>
                           </TableCell>
                        </TableRow>
                    </TableBody>
                </Table>
            </CardContent>
        </Card>
    );
}
